spring.application.name=authentication

spring.data.mongodb.host=host
spring.data.mongodb.port=XXXX
spring.data.mongodb.database=HHH


brevo.url=https://api.brevo.com/v3/smtp/email

brevo.sender.email=mdadilfaiz48@gmail.com
brevo.sender.name=AdilFaiz

# ==================== LOGGING CONFIGURATION ====================
# Enable DEBUG for authentication package
logging.level.com.auth=DEBUG

# =================Root logger level======================
logging.level.root=INFO

#====================== File logging configuration====================
logging.file.name=D:/authentication/logMessage.log
logging.file.max-size=10MB
logging.file.max-history=1

# ================Log pattern===========================
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# =======================Log levels for specific packages==============
logging.level.org.springframework=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.mongodb.driver=WARN



